//
// Created by u-0xffset on 21.12.20.
//

#ifndef MATHENGINESHAREDLIBRARY_SINESPECIALCASES_HPP
#define MATHENGINESHAREDLIBRARY_SINESPECIALCASES_HPP

#endif //MATHENGINESHAREDLIBRARY_SINESPECIALCASES_HPP
